# SonarQube Project Configuration
sonar.projectKey=Ambev.DeveloperEvaluation
sonar.projectName=Ambev.DeveloperEvaluation
sonar.projectVersion=1.0

# Path to sources
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

# Exclude projects/files from analysis
sonar.exclusions=**/Migrations/**/*.cs, **/obj/**, **/bin/**

# Exclude projects/files from coverage reports
sonar.coverage.exclusions=\
  **/*DTO.cs, \
  **/*Request.cs, \
  **/*Response.cs, \
  **/*Command.cs, \
  **/*Event.cs, \
  **/Migrations/**, \
  **/Entities/**, \
  **/Mapping/**, \
  **/IoC/**, \
  **/WebApi/Program.cs

# Path to coverage reports
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml, **/coverage.cobertura.xml, **/TestResults/**/*.xml
sonar.cs.vstest.reportsPaths=tests/**/TestResults/*.trx
